name: run main.py

on:
  schedule:
    - cron: '00 12 * * 6'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        run: python3 main.py

      - name: List files for debugging
        run: ls -la

      - name: Verify files for debugging
        run: |
          if [ ! -f driver_standings.csv ]; then echo "driver_standings.csv not found"; exit 1; fi
          if [ ! -f constructor_standings.csv ]; then echo "constructor_standings.csv not found"; exit 1; fi
          if [ ! -f race_results.csv ]; then echo "race_results.csv not found"; exit 1; fi
          if [ ! -f timestamp.txt ]; then echo "timestamp.txt not found"; exit 1; fi
          if [ ! -f next_race.txt ]; then echo "next_race.txt not found"; exit 1; fi

      - name: Show contents of files for debugging
        run: |
          echo "Contents of driver_standings.csv:"
          cat driver_standings.csv
          echo "Contents of constructor_standings.csv:"
          cat constructor_standings.csv
          echo "Contents of race_results.csv:"
          cat race_results.csv
          echo "Contents of timestamp.txt:"
          cat timestamp.txt
          echo "Contents of next_race.txt:"
          cat next_race.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add driver_standings.csv constructor_standings.csv race_results.csv timestamp.txt next_race.txt
          git diff-index --quiet HEAD || git commit -m "updated logs"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "updated logs"
          branch: main
          file_pattern: "*.csv, *.txt"
