name: run main.py

on:
  schedule:
    - cron: '0 12 * * 6'  # Runs at 12:00 PM UTC every Saturday
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check for requirements file
        id: check_requirements
        run: |
          if [ -f requirements.txt ]; then echo "requirements_exists=true" >> $GITHUB_ENV; else echo "requirements_exists=false" >> $GITHUB_ENV; fi

      - name: Install Python packages
        if: env.requirements_exists == 'true'
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Change to script directory
        run: cd ${{ github.workspace }}  # Adjust this path to match your repository structure

      - name: Execute Python script
        run: python3 main.py

      - name: List files for debugging
        run: ls -la

      - name: Verify files for debugging
        run: |
          if [ ! -f driver_standings.csv ]; then echo "driver_standings.csv not found"; exit 1; fi
          if [ ! -f constructor_standings.csv ]; then echo "constructor_standings.csv not found"; exit 1; fi
          if [ ! -f race_results.csv ]; then echo "race_results.csv not found"; exit 1; fi
          if [ ! -f timestamp.txt ]; then echo "timestamp.txt not found"; exit 1; fi
          if [ ! -f next_race.txt ]; then echo "next_race.txt not found"; exit 1; fi

      - name: Show contents of files for debugging
        run: |
          echo "Contents of driver_standings.csv:"
          cat driver_standings.csv
          echo "Contents of constructor_standings.csv:"
          cat constructor_standings.csv
          echo "Contents of race_results.csv:"
          cat race_results.csv
          echo "Contents of timestamp.txt:"
          cat timestamp.txt
          echo "Contents of next_race.txt:"
          cat next_race.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "updated logs" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.SFS_PAT }}@github.com/pmenright/SpoilerFreeSunday.git main
        continue-on-error: false

      - name: Debug push errors
        if: failure()
        run: |
          echo "Push failed. Checking recent commits..."
          git log -3 --oneline
          echo "Checking remote status..."
          git remote show origin
