name: run main.py

on:
  schedule:
    - cron: '13 22 * * *'  # Runs at 21:30 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3  # Updated to version that supports Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v4  # This version supports Node.js 20
        with:
          python-version: '3.9'  # Install the Python version needed

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        run: python main.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "updated logs"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4  # Updated push action
        with:
          commit_message: "updated logs"
          branch: main
          file_pattern: "logs/*"
