name: run main.py

on:
  schedule:
    - cron: '40 21 * * *'  # Runs at 21:30 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3  # Updated to version that supports Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v4  # This version should support Node.js 20
        with:
          python-version: '3.9'  # Install the Python version needed

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        run: python main.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: Push changes
        uses: github-actions-x/commit@v4  # Updated push action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
